# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Lectem's github
description: > # this means to ignore newlines until "baseurl:"
  Lectem's projects
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://lectem.github.io" # the base hostname & protocol for your site

twitter_username: lectem
github_username:  Lectem

# Build settings
markdown: kramdown

gems:
  - jekyll-redirect-from